export const tutorialData = [
  {
    "id": 1,
    "title": "Phishing Awareness Video",
    "description": "A whiteboard-style video explaining phishing attacks and how to avoid them.",
    "category": "privacy",
    "categoryName": "Privacy Protection",
    "image": "https://img.youtube.com/vi/QzLvq6FqCVY/hqdefault.jpg",
    "duration": "5 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/QzLvq6FqCVY"
  },
  {
    "id": 2,
    "title": "How to Stay Anonymous Online",
    "description": "Learn techniques to maintain online anonymity using tools like Tor.",
    "category": "privacy",
    "categoryName": "Privacy Protection",
    "image": "https://img.youtube.com/vi/3N8Q5TrUw04/hqdefault.jpg",
    "duration": "15 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/3N8Q5TrUw04"
  },
  {
    "id": 3,
    "title": "VPNs Explained",
    "description": "Understand how VPNs protect your privacy and how to choose one.",
    "category": "privacy",
    "categoryName": "Privacy Protection",
    "image": "https://img.youtube.com/vi/0Q3BZY4HKpU/hqdefault.jpg",
    "duration": "10 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/0Q3BZY4HKpU"
  },
  {
    "id": 4,
    "title": " Accessibility",
    "description": "Deep dive into advanced methods for online privacy.",
    "category": "privacy",
    "categoryName": "Privacy Protection",
    "image": "https://img.youtube.com/vi/7nL7oqXTLTs/hqdefault.jpg",
    "duration": "20 min",
    "level": "Advanced",
    "videoUrl": "https://www.youtube.com/embed/7nL7oqXTLTs"
  },
  {
    "id": 5,
    "title": "Social Media Privacy Settings",
    "description": "Guide to securing your social media accounts.",
    "category": "privacy",
    "categoryName": "Privacy Protection",
    "image": "https://img.youtube.com/vi/4jtcYPbvPUk/hqdefault.jpg",
    "duration": "10 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/4jtcYPbvPUk"
  },
  {
    "id": 6,
    "title": "Understanding Cookies and Tracking",
    "description": "How websites track you and ways to block trackers.",
    "category": "privacy",
    "categoryName": "Privacy Protection",
    "image": "https://img.youtube.com/vi/5e5yV7WIEF0/hqdefault.jpg",
    "duration": "12 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5e5yV7WIEF0"
  },
  {
    "id": 7,
    "title": "Secure Email Practices",
    "description": "Tips for protecting your email from phishing and hacks.",
    "category": "privacy",
    "categoryName": "Privacy Protection",
    "image": "https://img.youtube.com/vi/lc7scxvKQOo/hqdefault.jpg",
    "duration": "15 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/lc7scxvKQOo"
  },
  {
    "id": 8,
    "title": "Data Encryption for Privacy",
    "description": "Basics of encrypting your personal data.",
    "category": "privacy",
    "categoryName": "Privacy Protection",
    "image": "https://img.youtube.com/vi/AQDCe585Lnc/hqdefault.jpg",
    "duration": "10 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/AQDCe585Lnc"
  },
  {
    "id": 9,
    "title": "GDPR for Individuals",
    "description": "Overview of GDPR and your privacy rights.",
    "category": "privacy",
    "categoryName": "Privacy Protection",
    "image": "https://img.youtube.com/vi/1f3jB2F2x9c/hqdefault.jpg",
    "duration": "20 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/1f3jB2F2x9c"
  },
  {
    "id": 10,
    "title": "Mobile App Permissions",
    "description": "Managing app permissions to protect privacy.",
    "category": "privacy",
    "categoryName": "Privacy Protection",
    "image": "https://img.youtube.com/vi/m9unUb8Z9qU/hqdefault.jpg",
    "duration": "10 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/m9unUb8Z9qU"
  },
  {
    "id": 11,
    "title": "IoT Device Privacy",
    "description": "Securing smart home devices from privacy risks.",
    "category": "privacy",
    "categoryName": "Privacy Protection",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "15 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 12,
    "title": "Dark Web and Privacy",
    "description": "What is the dark web and its privacy implications?",
    "category": "privacy",
    "categoryName": "Privacy Protection",
    "image": "https://img.youtube.com/vi/3Kq1MIfTWCE/hqdefault.jpg",
    "duration": "20 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/3Kq1MIfTWCE"
  },
  {
    "id": 13,
    "title": "Secure File Sharing",
    "description": "How to share files privately and securely.",
    "category": "privacy",
    "categoryName": "Privacy Protection",
    "image": "https://img.youtube.com/vi/9iX9Y2Z3X9c/hqdefault.jpg",
    "duration": "10 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/9iX9Y2Z3X9c"
  },
  {
    "id": 14,
    "title": "Privacy-Focused Browsers",
    "description": "Exploring browsers designed for privacy.",
    "category": "privacy",
    "categoryName": "Privacy Protection",
    "image": "https://img.youtube.com/vi/5e5yV7WIEF0/hqdefault.jpg",
    "duration": "15 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5e5yV7WIEF0"
  },
  {
    "id": 15,
    "title": "Cloud Privacy Best Practices",
    "description": "Protecting your data in cloud services.",
    "category": "privacy",
    "categoryName": "Privacy Protection",
    "image": "https://img.youtube.com/vi/7nL7oqXTLTs/hqdefault.jpg",
    "duration": "20 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/7nL7oqXTLTs"
  },
  {
    "id": 16,
    "title": "Biometric Data Security",
    "description": "Safeguarding biometric information.",
    "category": "privacy",
    "categoryName": "Privacy Protection",
    "image": "https://img.youtube.com/vi/1f3jB2F2x9c/hqdefault.jpg",
    "duration": "25 min",
    "level": "Advanced",
    "videoUrl": "https://www.youtube.com/embed/1f3jB2F2x9c"
  },
  {
    "id": 17,
    "title": "Privacy in Messaging Apps",
    "description": "Choosing secure messaging apps for privacy.",
    "category": "privacy",
    "categoryName": "Privacy Protection",
    "image": "https://img.youtube.com/vi/5e5yV7WIEF0/hqdefault.jpg",
    "duration": "15 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5e5yV7WIEF0"
  },
  {
    "id": 18,
    "title": "Tor Network for Anonymity",
    "description": "Using Tor for anonymous browsing.",
    "category": "privacy",
    "categoryName": "Privacy Protection",
    "image": "https://img.youtube.com/vi/3N8Q5TrUw04/hqdefault.jpg",
    "duration": "20 min",
    "level": "Advanced",
    "videoUrl": "https://www.youtube.com/embed/3N8Q5TrUw04"
  },
  {
    "id": 19,
    "title": "Privacy Laws Overview",
    "description": "Key privacy laws and their impact.",
    "category": "privacy",
    "categoryName": "Privacy Protection",
    "image": "https://img.youtube.com/vi/1f3jB2F2x9c/hqdefault.jpg",
    "duration": "25 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/1f3jB2F2x9c"
  },
  {
    "id": 20,
    "title": "Ad Blockers for Privacy",
    "description": "Using ad blockers to reduce tracking.",
    "category": "privacy",
    "categoryName": "Privacy Protection",
    "image": "https://img.youtube.com/vi/5e5yV7WIEF0/hqdefault.jpg",
    "duration": "10 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/5e5yV7WIEF0"
  },
  {
    "id": 21,
    "title": "Password Security Basics",
    "description": "Creating and managing strong passwords.",
    "category": "security",
    "categoryName": "Security Basics",
    "image": "https://img.youtube.com/vi/a53gOGQrTyg/hqdefault.jpg",
    "duration": "10 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/a53gOGQrTyg"
  },
  {
    "id": 22,
    "title": "Two-Factor Authentication Setup",
    "description": "How to enable 2FA for account security.",
    "category": "security",
    "categoryName": "Security Basics",
    "image": "https://img.youtube.com/vi/4umI2BDQURk/hqdefault.jpg",
    "duration": "15 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/4umI2BDQURk"
  },
  {
    "id": 23,
    "title": "Introduction to Firewalls",
    "description": "What firewalls are and how they protect you.",
    "category": "security",
    "categoryName": "Security Basics",
    "image": "https://img.youtube.com/vi/E03gh1huvW4/hqdefault.jpg",
    "duration": "10 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/E03gh1huvW4"
  },
  {
    "id": 24,
    "title": "Antivirus Software Guide",
    "description": "Choosing and using antivirus tools.",
    "category": "security",
    "categoryName": "Security Basics",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "12 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 25,
    "title": "Malware Protection Tips",
    "description": "Identifying and preventing malware infections.",
    "category": "security",
    "categoryName": "Security Basics",
    "image": "https://img.youtube.com/vi/3Kq1MIfTWCE/hqdefault.jpg",
    "duration": "15 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/3Kq1MIfTWCE"
  },
  {
    "id": 26,
    "title": "Secure Wi-Fi Connections",
    "description": "Best practices for safe Wi-Fi usage.",
    "category": "security",
    "categoryName": "Security Basics",
    "image": "https://img.youtube.com/vi/5e5yV7WIEF0/hqdefault.jpg",
    "duration": "10 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/5e5yV7WIEF0"
  },
  {
    "id": 27,
    "title": "Software Update Importance",
    "description": "Why keeping software updated is critical.",
    "category": "security",
    "categoryName": "Security Basics",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "8 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 28,
    "title": "Backup Strategies",
    "description": "How to back up data securely.",
    "category": "security",
    "categoryName": "Security Basics",
    "image": "https://img.youtube.com/vi/9iX9Y2Z3X9c/hqdefault.jpg",
    "duration": "15 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/9iX9Y2Z3X9c"
  },
  {
    "id": 29,
    "title": "Social Engineering Defense",
    "description": "Spotting and avoiding social engineering attacks.",
    "category": "security",
    "categoryName": "Security Basics",
    "image": "https://img.youtube.com/vi/lc7scxvKQOo/hqdefault.jpg",
    "duration": "20 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/lc7scxvKQOo"
  },
  {
    "id": 30,
    "title": "Incident Response Basics",
    "description": "Steps to take after a security breach.",
    "category": "security",
    "categoryName": "Security Basics",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "25 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 31,
    "title": "Risk Assessment Intro",
    "description": "Identifying and managing security risks.",
    "category": "security",
    "categoryName": "Security Basics",
    "image": "https://img.youtube.com/vi/5e5yV7WIEF0/hqdefault.jpg",
    "duration": "20 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5e5yV7WIEF0"
  },
  {
    "id": 32,
    "title": "Security Policies 101",
    "description": "Understanding organizational security policies.",
    "category": "security",
    "categoryName": "Security Basics",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "15 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 33,
    "title": "Compliance Standards",
    "description": "Overview of common security standards.",
    "category": "security",
    "categoryName": "Security Basics",
    "image": "https://img.youtube.com/vi/1f3jB2F2x9c/hqdefault.jpg",
    "duration": "20 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/1f3jB2F2x9c"
  },
  {
    "id": 34,
    "title": "Encryption Fundamentals",
    "description": "How encryption secures your data.",
    "category": "security",
    "categoryName": "Security Basics",
    "image": "https://img.youtube.com/vi/AQDCe585Lnc/hqdefault.jpg",
    "duration": "15 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/AQDCe585Lnc"
  },
  {
    "id": 35,
    "title": "Secure Communication",
    "description": "Using secure channels for communication.",
    "category": "security",
    "categoryName": "Security Basics",
    "image": "https://img.youtube.com/vi/5e5yV7WIEF0/hqdefault.jpg",
    "duration": "15 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5e5yV7WIEF0"
  },
  {
    "id": 36,
    "title": "Identity Theft Prevention",
    "description": "Protecting against identity theft.",
    "category": "security",
    "categoryName": "Security Basics",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "10 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 37,
    "title": "Cybersecurity Laws",
    "description": "Key laws affecting cybersecurity.",
    "category": "security",
    "categoryName": "Security Basics",
    "image": "https://img.youtube.com/vi/1f3jB2F2x9c/hqdefault.jpg",
    "duration": "20 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/1f3jB2F2x9c"
  },
  {
    "id": 38,
    "title": "Threat Intelligence Intro",
    "description": "What is threat intelligence and its uses?",
    "category": "security",
    "categoryName": "Security Basics",
    "image": "https://img.youtube.com/vi/5e5yV7WIEF0/hqdefault.jpg",
    "duration": "25 min",
    "level": "Advanced",
    "videoUrl": "https://www.youtube.com/embed/5e5yV7WIEF0"
  },
  {
    "id": 39,
    "title": "Physical Security Basics",
    "description": "Protecting devices from physical threats.",
    "category": "security",
    "categoryName": "Security Basics",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "10 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 40,
    "title": "Endpoint Security",
    "description": "Securing devices like laptops and phones.",
    "category": "security",
    "categoryName": "Security Basics",
    "image": "https://img.youtube.com/vi/5e5yV7WIEF0/hqdefault.jpg",
    "duration": "15 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5e5yV7WIEF0"
  },
  {
    "id": 41,
    "title": "Secure Coding Principles",
    "description": "Best practices for writing secure code.",
    "category": "coding",
    "categoryName": "Secure Coding",
    "image": "https://img.youtube.com/vi/qjrkV4RAdEY/hqdefault.jpg",
    "duration": "20 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/qjrkV4RAdEY"
  },
  {
    "id": 42,
    "title": "SQL Injection Prevention",
    "description": "How to avoid SQL injection vulnerabilities.",
    "category": "coding",
    "categoryName": "Secure Coding",
    "image": "https://img.youtube.com/vi/fvcKwUS4PTE/hqdefault.jpg",
    "duration": "15 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/fvcKwUS4PTE"
  },
  {
    "id": 43,
    "title": "Cross-Site Scripting (XSS)",
    "description": "Preventing XSS attacks in web apps.",
    "category": "coding",
    "categoryName": "Secure Coding",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "15 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 44,
    "title": "Input Validation Techniques",
    "description": "Validating inputs to prevent attacks.",
    "category": "coding",
    "categoryName": "Secure Coding",
    "image": "https://img.youtube.com/vi/5e5yV7WIEF0/hqdefault.jpg",
    "duration": "10 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/5e5yV7WIEF0"
  },
  {
    "id": 45,
    "title": "Secure Coding in Python",
    "description": "Secure coding practices for Python.",
    "category": "coding",
    "categoryName": "Secure Coding",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "20 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 46,
    "title": "Error Handling Best Practices",
    "description": "Secure error handling in applications.",
    "category": "coding",
    "categoryName": "Secure Coding",
    "image": "https://img.youtube.com/vi/5e5yV7WIEF0/hqdefault.jpg",
    "duration": "15 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5e5yV7WIEF0"
  },
  {
    "id": 47,
    "title": "Authentication Mechanisms",
    "description": "Implementing secure authentication.",
    "category": "coding",
    "categoryName": "Secure Coding",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "20 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 48,
    "title": "Authorization Controls",
    "description": "Setting up secure authorization.",
    "category": "coding",
    "categoryName": "Secure Coding",
    "image": "https://img.youtube.com/vi/5e5yV7WIEF0/hqdefault.jpg",
    "duration": "15 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 49,
    "title": "Session Management Security",
    "description": "Securing user sessions in apps.",
    "category": "coding",
    "categoryName": "Secure Coding",
    "image": "https://img.youtube.com/vi/5e5yV7WIEF0/hqdefault.jpg",
    "duration": "15 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5e5yV7WIEF0"
  },
  {
    "id": 50,
    "title": "Cryptography in Coding",
    "description": "Using cryptography in software development.",
    "category": "coding",
    "categoryName": "Secure Coding",
    "image": "https://img.youtube.com/vi/AQDCe585Lnc/hqdefault.jpg",
    "duration": "20 min",
    "level": "Advanced",
    "videoUrl": "https://www.youtube.com/embed/AQDCe585Lnc"
  },
  {
    "id": 51,
    "title": "Secure API Development",
    "description": "Building secure APIs for applications.",
    "category": "coding",
    "categoryName": "Secure Coding",
    "image": "https://img.youtube.com/vi/fvcKwUS4PTE/hqdefault.jpg",
    "duration": "20 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/fvcKwUS4PTE"
  },
  {
    "id": 52,
    "title": "Code Review for Security",
    "description": "Reviewing code for security flaws.",
    "category": "coding",
    "categoryName": "Secure Coding",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "15 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 53,
    "title": "Static Code Analysis",
    "description": "Using tools to analyze code security.",
    "category": "coding",
    "categoryName": "Secure Coding",
    "image": "https://img.youtube.com/vi/5e5yV7WIEF0/hqdefault.jpg",
    "duration": "20 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 54,
    "title": "Dynamic Code Analysis",
    "description": "Testing code security at runtime.",
    "category": "coding",
    "categoryName": "Secure Coding",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "25 min",
    "level": "Advanced",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 55,
    "title": "OWASP Top 10 Overview",
    "description": "Understanding the top 10 web security risks.",
    "category": "coding",
    "categoryName": "Secure Coding",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "20 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 56,
    "title": "Buffer Overflow Prevention",
    "description": "Avoiding buffer overflow vulnerabilities.",
    "category": "coding",
    "categoryName": "Secure Coding",
    "image": "https://img.youtube.com/vi/5e5yV7WIEF0/hqdefault.jpg",
    "duration": "25 min",
    "level": "Advanced",
    "videoUrl": "https://www.youtube.com/embed/5e5yV7WIEF0"
  },
  {
    "id": 57,
    "title": "Secure Coding in Java",
    "description": "Secure coding practices for Java developers.",
    "category": "coding",
    "categoryName": "Secure Coding",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "20 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 58,
    "title": "Mobile App Security",
    "description": "Securing mobile applications.",
    "category": "coding",
    "categoryName": "Secure Coding",
    "image": "https://img.youtube.com/vi/m9unUb8Z9qU/hqdefault.jpg",
    "duration": "15 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/m9unUb8Z9qU"
  },
  {
    "id": 59,
    "title": "Web Application Security",
    "description": "Protecting web apps from common threats.",
    "category": "coding",
    "categoryName": "Secure Coding",
    "image": "https://img.youtube.com/vi/qjrkV4RAdEY/hqdefault.jpg",
    "duration": "20 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/qjrkV4RAdEY"
  },
  {
    "id": 60,
    "title": "Secure SDLC",
    "description": "Integrating security into the SDLC.",
    "category": "coding",
    "categoryName": "Secure Coding",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "25 min",
    "level": "Advanced",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 61,
    "title": "Network Security Fundamentals",
    "description": "Basics of securing computer networks.",
    "category": "network",
    "categoryName": "Network Security",
    "image": "https://img.youtube.com/vi/E03gh1huvW4/hqdefault.jpg",
    "duration": "15 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/E03gh1huvW4"
  },
  {
    "id": 62,
    "title": "Secure Home Network Setup",
    "description": "Configuring a secure home network.",
    "category": "network",
    "categoryName": "Network Security",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "10 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 63,
    "title": "Intrusion Detection Systems",
    "description": "How IDS detect network threats.",
    "category": "network",
    "categoryName": "Network Security",
    "image": "https://img.youtube.com/vi/5e5yV7WIEF0/hqdefault.jpg",
    "duration": "20 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5e5yV7WIEF0"
  },
  {
    "id": 64,
    "title": "VPN Configuration Guide",
    "description": "Setting up a VPN for secure networking.",
    "category": "network",
    "categoryName": "Network Security",
    "image": "https://img.youtube.com/vi/0Q3BZY4HKpU/hqdefault.jpg",
    "duration": "15 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/0Q3BZY4HKpU"
  },
  {
    "id": 65,
    "title": "Network Segmentation",
    "description": "Segmenting networks for security.",
    "category": "network",
    "categoryName": "Network Security",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "20 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 66,
    "title": "Wireless Network Security",
    "description": "Securing Wi-Fi networks.",
    "category": "network",
    "categoryName": "Network Security",
    "image": "https://img.youtube.com/vi/5e5yV7WIEF0/hqdefault.jpg",
    "duration": "15 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/5e5yV7WIEF0"
  },
  {
    "id": 67,
    "title": "Network Monitoring Tools",
    "description": "Using tools to monitor network traffic.",
    "category": "network",
    "categoryName": "Network Security",
    "image": "https://img.youtube.com/vi/TkCSr30UojM/hqdefault.jpg",
    "duration": "20 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/TkCSr30UojM"
  },
  {
    "id": 68,
    "title": "Vulnerability Scanning",
    "description": "Scanning networks for vulnerabilities.",
    "category": "network",
    "categoryName": "Network Security",
    "image": "https://img.youtube.com/vi/4t4kBkMsDbQ/hqdefault.jpg",
    "duration": "15 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/4t4kBkMsDbQ"
  },
  {
    "id": 69,
    "title": "Secure Network Design",
    "description": "Principles of designing secure networks.",
    "category": "network",
    "categoryName": "Network Security",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "25 min",
    "level": "Advanced",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 70,
    "title": "DNS Security Practices",
    "description": "Securing DNS operations.",
    "category": "network",
    "categoryName": "Network Security",
    "image": "https://img.youtube.com/vi/5e5yV7WIEF0/hqdefault.jpg",
    "duration": "15 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5e5yV7WIEF0"
  },
  {
    "id": 71,
    "title": "DHCP Security",
    "description": "Securing DHCP services.",
    "category": "network",
    "categoryName": "Network Security",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "15 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 72,
    "title": "NAT and PAT Basics",
    "description": "Understanding NAT and PAT for security.",
    "category": "network",
    "categoryName": "Network Security",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "10 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 73,
    "title": "Proxy Servers for Security",
    "description": "Using proxies to enhance network security.",
    "category": "network",
    "categoryName": "Network Security",
    "image": "https://img.youtube.com/vi/5e5yV7WIEF0/hqdefault.jpg",
    "duration": "10 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/5e5yV7WIEF0"
  },
  {
    "id": 74,
    "title": "Load Balancer Security",
    "description": "Securing load balancers in networks.",
    "category": "network",
    "categoryName": "Network Security",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "20 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 75,
    "title": "Network Access Control",
    "description": "Implementing NAC for network security.",
    "category": "network",
    "categoryName": "Network Security",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "20 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 76,
    "title": "IPv6 Security Concerns",
    "description": "Security considerations for IPv6.",
    "category": "network",
    "categoryName": "Network Security",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "25 min",
    "level": "Advanced",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 77,
    "title": "Cloud Network Security",
    "description": "Securing cloud-based networks.",
    "category": "network",
    "categoryName": "Network Security",
    "image": "https://img.youtube.com/vi/7nL7oqXTLTs/hqdefault.jpg",
    "duration": "20 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/7nL7oqXTLTs"
  },
  {
    "id": 78,
    "title": "SD-WAN Security",
    "description": "Security in software-defined WAN.",
    "category": "network",
    "categoryName": "Network Security",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "25 min",
    "level": "Advanced",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 79,
    "title": "Zero Trust Architecture",
    "description": "Implementing zero trust in networks.",
    "category": "network",
    "categoryName": "Network Security",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "30 min",
    "level": "Advanced",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 80,
    "title": "Network Penetration Testing",
    "description": "Testing network security with pen tests.",
    "category": "network",
    "categoryName": "Network Security",
    "image": "https://img.youtube.com/vi/4t4kBkMsDbQ/hqdefault.jpg",
    "duration": "25 min",
    "level": "Advanced",
    "videoUrl": "https://www.youtube.com/embed/4t4kBkMsDbQ"
  },
  {
    "id": 81,
    "title": "Ethical Hacking Introduction",
    "description": "What is ethical hacking and its benefits?",
    "category": "hacking",
    "categoryName": "Ethical Hacking",
    "image": "https://img.youtube.com/vi/3Kq1MIfTWCE/hqdefault.jpg",
    "duration": "15 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/3Kq1MIfTWCE"
  },
  {
    "id": 82,
    "title": "Reconnaissance Techniques",
    "description": "Gathering info for ethical hacking.",
    "category": "hacking",
    "categoryName": "Ethical Hacking",
    "image": "https://img.youtube.com/vi/u9BRyNW7mo8/hqdefault.jpg",
    "duration": "20 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/u9BRyNW7mo8"
  },
  {
    "id": 83,
    "title": "Nmap for Network Scanning",
    "description": "Using Nmap to scan networks.",
    "category": "hacking",
    "categoryName": "Ethical Hacking",
    "image": "https://img.youtube.com/vi/4t4kBkMsDbQ/hqdefault.jpg",
    "duration": "15 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/4t4kBkMsDbQ"
  },
  {
    "id": 84,
    "title": "Metasploit Basics",
    "description": "Using Metasploit for penetration testing.",
    "category": "hacking",
    "categoryName": "Ethical Hacking",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "25 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 85,
    "title": "Enumeration Techniques",
    "description": "Extracting info from target systems.",
    "category": "hacking",
    "categoryName": "Ethical Hacking",
    "image": "https://img.youtube.com/vi/5e5yV7WIEF0/hqdefault.jpg",
    "duration": "20 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5e5yV7WIEF0"
  },
  {
    "id": 86,
    "title": "System Hacking Intro",
    "description": "Basics of ethical system hacking.",
    "category": "hacking",
    "categoryName": "Ethical Hacking",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "15 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 87,
    "title": "Web App Penetration Testing",
    "description": "Testing web apps for vulnerabilities.",
    "category": "hacking",
    "categoryName": "Ethical Hacking",
    "image": "https://img.youtube.com/vi/qjrkV4RAdEY/hqdefault.jpg",
    "duration": "25 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/qjrkV4RAdEY"
  },
  {
    "id": 88,
    "title": "Wireless Hacking Basics",
    "description": "Introduction to hacking wireless networks.",
    "category": "hacking",
    "categoryName": "Ethical Hacking",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "20 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 89,
    "title": "Social Engineering Attacks",
    "description": "How hackers exploit human psychology.",
    "category": "hacking",
    "categoryName": "Ethical Hacking",
    "image": "https://img.youtube.com/vi/lc7scxvKQOo/hqdefault.jpg",
    "duration": "15 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/lc7scxvKQOo"
  },
  {
    "id": 90,
    "title": "Post-Exploitation Techniques",
    "description": "Actions after gaining system access.",
    "category": "hacking",
    "categoryName": "Ethical Hacking",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "30 min",
    "level": "Advanced",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 91,
    "title": "Hacking Documentation",
    "description": "Documenting ethical hacking findings.",
    "category": "hacking",
    "categoryName": "Ethical Hacking",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "15 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 92,
    "title": "Legal Aspects of Hacking",
    "description": "Laws governing ethical hacking.",
    "category": "hacking",
    "categoryName": "Ethical Hacking",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "20 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 93,
    "title": "CTF Challenges Intro",
    "description": "Getting started with Capture the Flag.",
    "category": "hacking",
    "categoryName": "Ethical Hacking",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "15 min",
    "level": "Beginner",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 94,
    "title": "Bug Bounty Basics",
    "description": "How to participate in bug bounty programs.",
    "category": "hacking",
    "categoryName": "Ethical Hacking",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "20 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 95,
    "title": "Red Teaming Overview",
    "description": "Introduction to red team operations.",
    "category": "hacking",
    "categoryName": "Ethical Hacking",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "25 min",
    "level": "Advanced",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 96,
    "title": "Blue Teaming Basics",
    "description": "Defending against attacks as a blue team.",
    "category": "hacking",
    "categoryName": "Ethical Hacking",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "20 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 97,
    "title": "Purple Teaming",
    "description": "Combining red and blue team efforts.",
    "category": "hacking",
    "categoryName": "Ethical Hacking",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "25 min",
    "level": "Advanced",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 98,
    "title": "Reverse Engineering Intro",
    "description": "Basics of reverse engineering software.",
    "category": "hacking",
    "categoryName": "Ethical Hacking",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "30 min",
    "level": "Advanced",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 99,
    "title": "Malware Analysis Basics",
    "description": "Introduction to analyzing malware.",
    "category": "hacking",
    "categoryName": "Ethical Hacking",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "25 min",
    "level": "Intermediate",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  },
  {
    "id": 100,
    "title": "Digital Forensics Overview",
    "description": "Basics of investigating cyber incidents.",
    "category": "hacking",
    "categoryName": "Ethical Hacking",
    "image": "https://img.youtube.com/vi/5y5qV7WIEF0/hqdefault.jpg",
    "duration": "30 min",
    "level": "Advanced",
    "videoUrl": "https://www.youtube.com/embed/5y5qV7WIEF0"
  }
]