export const tutorialData = [
  {
    id: 1,
    title: "Phishing Awareness Training",
    description:
      "Learn to identify and avoid common phishing attacks targeting individuals and organizations.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/XBkzBrXlle0/hqdefault.jpg",
    duration: "6 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/XBkzBrXlle0",
    dateAdded: "2023-06-01",
  },
  {
    id: 2,
    title: "How to Stay Anonymous Online",
    description:
      "Techniques to maintain online anonymity and protect your digital privacy.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/jxeeKKfjb5o/hqdefault.jpg",
    duration: "12 min",
    level: "Intermediate",
    videoUrl: "https://www.youtube.com/embed/jxeeKKfjb5o",
    dateAdded: "2023-06-01",
  },
  {
    id: 3,
    title: "VPNs Explained",
    description:
      "Understand how VPNs protect your privacy and how to choose the right one.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/WVDQEoe6ZWY/hqdefault.jpg",
    duration: "11 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/WVDQEoe6ZWY",
    dateAdded: "2023-06-01",
  },
  {
    id: 4,
    title: "Protect Your Privacy: 2 Simple Ways to Secure Facebook Profiles",
    description:
      "Step-by-step walkthrough for adjusting privacy controls across Facebook, Twitter, LinkedIn, and Instagram.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/TNp9J5lKzco/hqdefault.jpg",
    duration: "6 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/TNp9J5lKzco",
    dateAdded: "2024-10-05",
  },
  {
    id: 5,
    title: "Understanding Cookies and Tracking",
    description:
      "An explanation of how cookies work and their role in online tracking.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/IPQhME1UYQU/hqdefault.jpg",
    duration: "5 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/IPQhME1UYQU",
    dateAdded: "2023-06-01",
  },
  {
    id: 6,
    title: "Cybersecurity for Beginners: Basic Skills",
    description:
      "Introduction to essential cybersecurity skills and practices for individuals, covering how to avoid common threats like scams and malware.",
    category: "basics",
    categoryName: "Cybersecurity Basics",
    image: "https://img.youtube.com/vi/aRbKFCY4tjE/hqdefault.jpg",
    duration: "6 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/aRbKFCY4tjE",
    dateAdded: "2025-05-02",
  },
  {
    id: 7,
    title: "Data Encryption Basics",
    description:
      "Introduction to encrypting data to protect it from unauthorized access.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/o_g-M7UBqI8/hqdefault.jpg",
    duration: "10 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/o_g-M7UBqI8",
    dateAdded: "2023-06-01",
  },
  {
    id: 8,
    title: "GDPR for Individuals",
    description:
      "Understand your rights under the General Data Protection Regulation.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/j6wwBqfSk-o/hqdefault.jpg",
    duration: "9 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/j6wwBqfSk-o",
    dateAdded: "2023-06-01",
  },
  {
    id: 9,
    title: "Managing App Permissions on Android",
    description:
      "Essential guide to review and revoke Android app permissions for better privacy.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/0gtE3_KG2tk/hqdefault.jpg",
    duration: "7 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/0gtE3_KG2tk",
    dateAdded: "2024-11-01",
  },
  {
    id: 10,
    title: "IoT Device Privacy and Security",
    description: "Securing Internet of Things devices in your home.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/7zWVxrjjIpE/hqdefault.jpg",
    duration: "8 min",
    level: "Intermediate",
    videoUrl: "https://www.youtube.com/embed/7zWVxrjjIpE",
    dateAdded: "2023-06-01",
  },
  {
    id: 11,
    title: "Password Security Fundamentals",
    description: "Learn how to create and manage strong passwords.",
    category: "basics",
    categoryName: "Security Basics",
    image: "https://i.ytimg.com/vi/aHaBH4LqGsI/hqdefault.jpg",
    duration: "7 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/aHaBH4LqGsI",
    dateAdded: "2023-06-01",
  },
  {
    id: 12,
    title: "How to Set Up Two-Factor Authentication (2FA)",
    description:
      "Beginner's guide to enabling 2FA across Google, Facebook, and other platforms.",
    category: "basics",
    categoryName: "Security Basics",
    image: "https://i.ytimg.com/vi/hlpoc3C1kWM/hqdefault.jpg",
    duration: "9 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/hlpoc3C1kWM",
    dateAdded: "2021-11-05",
  },
  {
    id: 13,
    title: "Understanding the Basics of a Firewall",
    description:
      "Network-essentials overview of how firewalls monitor traffic and enforce rules.",
    category: "basics",
    categoryName: "Security Basics",
    image: "https://i.ytimg.com/vi/Fli0GD_9OEU/hqdefault.jpg",
    duration: "8 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/Fli0GD_9OEU",
    dateAdded: "2022-03-15",
  },
  {
    id: 14,
    title: "Top 5 Free Antivirus Software for Windows 10 (2024)",
    description:
      "Comparison of leading free antivirus tools that you can install today.",
    category: "basics",
    categoryName: "Security Basics",
    image: "https://i.ytimg.com/vi/VWZV4r_5ZHE/hqdefault.jpg",
    duration: "10 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/VWZV4r_5ZHE",
    dateAdded: "2024-03-28",
  },
  {
    id: 15,
    title: "What Is Ransomware? | Ransomware Attack",
    description:
      "Explains how ransomware works, including how it encrypts files and demands payment, and outlines basic steps for protection and recovery.",
    category: "basics",
    categoryName: "Cybersecurity Basics",
    image: "https://img.youtube.com/vi/-KL9APUjj3E/hqdefault.jpg",
    duration: "6 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/-KL9APUjj3E",
    dateAdded: "2025-05-02",
  },
  {
    id: 16,
    title: "What Is Malware? Let's Hear the Hacker's Viewpoint",
    description:
      "Discusses the nature of malware from a security perspective, covering how malicious software infects systems and spreads, with insights on detection.",
    category: "basics",
    categoryName: "Cybersecurity Basics",
    image: "https://img.youtube.com/vi/mqzP7gJDM2s/hqdefault.jpg",
    duration: "6 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/mqzP7gJDM2s",
    dateAdded: "2025-05-02",
  },
  {
    id: 17,
    title: "Top 10 Facts About Phishing in 2023",
    description:
      "Presents key statistics and facts about phishing attacks in 2023 to raise awareness of the threat and encourage vigilant email practices.",
    category: "basics",
    categoryName: "Cybersecurity Basics",
    image: "https://img.youtube.com/vi/gnrqVTAOYs8/hqdefault.jpg",
    duration: "5 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/gnrqVTAOYs8",
    dateAdded: "2025-05-02",
  },
  {
    id: 18,
    title: "Essential Cybersecurity Best Practices",
    description:
      "Short guide covering essential cybersecurity habits like using strong passwords, enabling updates, and being cautious with links to protect against common threats.",
    category: "basics",
    categoryName: "Cybersecurity Basics",
    image: "https://img.youtube.com/vi/-fmTr9E0jJg/hqdefault.jpg",
    duration: "3 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/-fmTr9E0jJg",
    dateAdded: "2025-05-02",
  },
  {
    id: 19,
    title: "Social Engineering Defense",
    description: "Protect yourself from social engineering attacks.",
    category: "basics",
    categoryName: "Security Basics",
    image: "https://i.ytimg.com/vi/lc7scxvKQOo/hqdefault.jpg",
    duration: "7 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/lc7scxvKQOo",
    dateAdded: "2023-06-01",
  },
  {
    id: 20,
    title: "Top 3 Password Managers for 2023 | How to Keep Your Passwords Safe",
    description:
      "Review of three leading password managers with recommendations on how to securely store and manage complex passwords in 2023.",
    category: "basics",
    categoryName: "Cybersecurity Basics",
    image: "https://img.youtube.com/vi/ARwUJ-2v42c/hqdefault.jpg",
    duration: "22 min",
    level: "Intermediate",
    videoUrl: "https://www.youtube.com/embed/ARwUJ-2v42c",
    dateAdded: "2025-05-02",
  },
  {
    id: 21,
    title: "Secure Coding Back to Basics - NDC Security 2022",
    description:
      "Conference talk outlining foundational secure coding practices developers should follow to avoid introducing vulnerabilities in software.",
    category: "coding",
    categoryName: "Secure Coding",
    image: "https://img.youtube.com/vi/ce3VBNrzRSE/hqdefault.jpg",
    duration: "13 min",
    level: "Advanced",
    videoUrl: "https://www.youtube.com/embed/ce3VBNrzRSE",
    dateAdded: "2025-05-02",
  },
  {
    id: 22,
    title: "SQL Injection Prevention",
    description: "Techniques to prevent SQL injection attacks.",
    category: "coding",
    categoryName: "Secure Coding",
    image: "https://i.ytimg.com/vi/cx6Xs3F_1Uc/hqdefault.jpg",
    duration: "10 min",
    level: "Intermediate",
    videoUrl: "https://www.youtube.com/embed/cx6Xs3F_1Uc",
    dateAdded: "2023-06-01",
  },
  {
    id: 23,
    title: "Cross-Site Scripting (XSS) Defense",
    description: "Defend applications against XSS vulnerabilities.",
    category: "coding",
    categoryName: "Secure Coding",
    image: "https://i.ytimg.com/vi/ns1LX6mEvyM/hqdefault.jpg",
    duration: "9 min",
    level: "Intermediate",
    videoUrl: "https://www.youtube.com/embed/ns1LX6mEvyM",
    dateAdded: "2023-06-01",
  },
  {
    id: 24,
    title: "OWASP Top 10 2021 Explained | Web Application Vulnerabilities",
    description:
      "Walks through the OWASP Top 10 2021 web security risks (like injection, broken auth) and how developers can mitigate them.",
    category: "coding",
    categoryName: "Secure Coding",
    image: "https://img.youtube.com/vi/kdTkj6DdbCg/hqdefault.jpg",
    duration: "11 min",
    level: "Intermediate",
    videoUrl: "https://www.youtube.com/embed/kdTkj6DdbCg",
    dateAdded: "2025-05-02",
  },
  {
    id: 25,
    title: "Your Smart Home Is Stupid - IoT Security Explained",
    description:
      "Explains why common Internet of Things (IoT) devices can be vulnerable, and suggests ways to better secure your smart home network.",
    category: "network",
    categoryName: "Network Security",
    image: "https://img.youtube.com/vi/SvFyd8DpRkw/hqdefault.jpg",
    duration: "7 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/SvFyd8DpRkw",
    dateAdded: "2025-05-02",
  },
  {
    id: 26,
    title: "WiFi Security Myths Demo: Don't Believe These Will Protect You!",
    description:
      "Demonstration debunking common myths about Wi-Fi protection, showing practical steps to secure a wireless network against attackers.",
    category: "network",
    categoryName: "Network Security",
    image: "https://img.youtube.com/vi/ucal07Y9q_s/hqdefault.jpg",
    duration: "15 min",
    level: "Intermediate",
    videoUrl: "https://www.youtube.com/embed/ucal07Y9q_s",
    dateAdded: "2025-05-02",
  },
  {
    id: 27,
    title: "Secure Authentication Implementation",
    description: "Implement secure authentication in applications.",
    category: "coding",
    categoryName: "Secure Coding",
    image: "https://i.ytimg.com/vi/j8Yxff6L_po/hqdefault.jpg",
    duration: "10 min",
    level: "Intermediate",
    videoUrl: "https://www.youtube.com/embed/j8Yxff6L_po",
    dateAdded: "2023-06-01",
  },
  {
    id: 28,
    title: "What Is Penetration Testing and How Does It Work?",
    description:
      "Introduction to penetration testing (ethical hacking), explaining how security experts simulate attacks to find vulnerabilities before malicious hackers do.",
    category: "hacking",
    categoryName: "Ethical Hacking",
    image: "https://img.youtube.com/vi/TPKkTtcCACQ/hqdefault.jpg",
    duration: "8 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/TPKkTtcCACQ",
    dateAdded: "2025-05-02",
  },
  {
    id: 29,
    title: "Data Security 101: Protecting Your Online Privacy",
    description:
      "Basic tips on how to safeguard personal data and maintain privacy online, such as using strong passwords, encryption, and privacy-friendly tools.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://img.youtube.com/vi/ZJeBgyq7vQw/hqdefault.jpg",
    duration: "10 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/ZJeBgyq7vQw",
    dateAdded: "2025-05-02",
  },
  {
    id: 30,
    title: "Cryptography for Developers",
    description:
      "Use cryptographic building blocks without making common mistakes.",
    category: "coding",
    categoryName: "Secure Coding",
    image: "https://i.ytimg.com/vi/NuyzuNBFWxQ/hqdefault.jpg",
    duration: "15 min",
    level: "Advanced",
    videoUrl: "https://www.youtube.com/embed/NuyzuNBFWxQ",
    dateAdded: "2023-06-01",
  },
  {
    id: 31,
    title: "Network Security Fundamentals",
    description: "Basics of securing computer networks.",
    category: "network",
    categoryName: "Network Security",
    image: "https://i.ytimg.com/vi/VznoKyh6AXs/hqdefault.jpg",
    duration: "10 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/VznoKyh6AXs",
    dateAdded: "2023-06-01",
  },
  {
    id: 32,
    title: "What is a VPN? (Virtual Private Network Explained)",
    description:
      "Covers the basics of VPNs (Virtual Private Networks), including how they encrypt your connection and why they are used to improve online security and privacy.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://img.youtube.com/vi/tJJ37XYsTac/hqdefault.jpg",
    duration: "5 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/tJJ37XYsTac",
    dateAdded: "2025-05-02",
  },
  {
    id: 33,
    title: "What Is Firewall | Types of Firewall (Network Security)",
    description:
      "Explains what network firewalls are, the different types (software, hardware, next-gen), and how they act as a barrier to block unauthorized access.",
    category: "network",
    categoryName: "Network Security",
    image: "https://img.youtube.com/vi/Xb0AJ1ORACo/hqdefault.jpg",
    duration: "5 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/Xb0AJ1ORACo",
    dateAdded: "2025-05-02",
  },
  {
    id: 34,
    title: "VPN Configuration Guide",
    description:
      "Step-by-step guide to configuring OpenVPN on Windows and Linux.",
    category: "network",
    categoryName: "Network Security",
    image: "https://i.ytimg.com/vi/gxpX_mubz2A/hqdefault.jpg",
    duration: "9 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/gxpX_mubz2A",
    dateAdded: "2023-06-01",
  },
  {
    id: 35,
    title: "What Is Cryptography? (Encryption Basics Explained)",
    description:
      "Overview of cryptography, covering symmetric and asymmetric encryption, hashing, and how these techniques protect data in software and communications.",
    category: "coding",
    categoryName: "Secure Coding",
    image: "https://img.youtube.com/vi/OcUzqwzjWNE/hqdefault.jpg",
    duration: "7 min",
    level: "Intermediate",
    videoUrl: "https://www.youtube.com/embed/OcUzqwzjWNE",
    dateAdded: "2025-05-02",
  },
  {
    id: 36,
    title: "Social engineering: Keep I.T. Confidential",
    description:
      "Illustrative video on social engineering, showing how attackers use deception to trick people into revealing confidential information and how to stay safe.",
    category: "hacking",
    categoryName: "Ethical Hacking",
    image: "https://img.youtube.com/vi/wAC0fN3z1Es/hqdefault.jpg",
    duration: "1 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/wAC0fN3z1Es",
    dateAdded: "2025-05-02",
  },
  {
    id: 37,
    title: "What Is the Dark Web? A Guide to the Dark Side of the Internet",
    description:
      "Explains what the Dark Web is, how it operates on the Tor network, and why it poses privacy and security considerations for everyday users.",
    category: "hacking",
    categoryName: "Ethical Hacking",
    image: "https://img.youtube.com/vi/N3-zrhoBx6w/hqdefault.jpg",
    duration: "8 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/N3-zrhoBx6w",
    dateAdded: "2025-05-02",
  },
  {
    id: 38,
    title: "What Is Two-Factor Authentication? (2FA Explained)",
    description:
      "Introduces two-factor authentication (2FA) and why adding a second verification step improves security over simple passwords.",
    category: "basics",
    categoryName: "Cybersecurity Basics",
    image: "https://img.youtube.com/vi/0mvCeNsTa1g/hqdefault.jpg",
    duration: "5 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/0mvCeNsTa1g",
    dateAdded: "2025-05-02",
  },
  {
    id: 39,
    title: "What Is Intrusion Detection System? (IDS Explained)",
    description:
      "Covers the concept of an Intrusion Detection System (IDS), describing how IDS monitors network traffic for suspicious activity and alerts defenders.",
    category: "network",
    categoryName: "Network Security",
    image: "https://img.youtube.com/vi/dfVAi87BSEs/hqdefault.jpg",
    duration: "5 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/dfVAi87BSEs",
    dateAdded: "2025-05-02",
  },
  {
    id: 40,
    title: "What Is Data Protection & Privacy? Learn the Basics",
    description:
      "An introduction to data protection and privacy principles, including why protecting personal data matters and how privacy laws like GDPR impact users.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://img.youtube.com/vi/mMXdpXouSLo/hqdefault.jpg",
    duration: "7 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/mMXdpXouSLo",
    dateAdded: "2025-05-02",
  },
  {
    id: 41,
    title: "Ethical Hacking for Beginners",
    description: "Overview of ethical hacking and its importance.",
    category: "hacking",
    categoryName: "Ethical Hacking",
    image: "https://i.ytimg.com/vi/X50Qkm9-d8M/hqdefault.jpg",
    duration: "15 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/X50Qkm9-d8M",
    dateAdded: "2024-03-18",
  },
  {
    id: 42,
    title: "Think Before You Click! Protect Yourself from Phishing",
    description:
      "Awareness message reminding viewers to scrutinize email links and attachments to avoid falling victim to phishing scams.",
    category: "basics",
    categoryName: "Cybersecurity Basics",
    image: "https://img.youtube.com/vi/IwQTtvAHFpc/hqdefault.jpg",
    duration: "2 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/IwQTtvAHFpc",
    dateAdded: "2025-05-02",
  },
  {
    id: 43,
    title: "Nmap for Network Scanning",
    description: "Use Nmap to scan networks for vulnerabilities.",
    category: "hacking",
    categoryName: "Ethical Hacking",
    image: "https://i.ytimg.com/vi/5MTZdN9TEO4/hqdefault.jpg",
    duration: "10 min",
    level: "Intermediate",
    videoUrl: "https://www.youtube.com/embed/5MTZdN9TEO4",
    dateAdded: "2023-06-01",
  },
  {
    id: 44,
    title: "Metasploit Basics",
    description: "Introduction to using Metasploit for penetration testing.",
    category: "hacking",
    categoryName: "Ethical Hacking",
    image: "https://i.ytimg.com/vi/TCPyoWHy4eA/hqdefault.jpg",
    duration: "13 min",
    level: "Intermediate",
    videoUrl: "https://www.youtube.com/embed/TCPyoWHy4eA",
    dateAdded: "2023-06-01",
  },
  {
    id: 45,
    title: "Your Home Network is Exposed: Top 10 Ways to Protect it NOW!",
    description:
      "Lists ten practical ways to secure a home network (like using a secure router, disabling WPS, using a VPN) against intruders and eavesdroppers.",
    category: "network",
    categoryName: "Network Security",
    image: "https://img.youtube.com/vi/ivPptt3Ae5o/hqdefault.jpg",
    duration: "10 min",
    level: "Intermediate",
    videoUrl: "https://www.youtube.com/embed/ivPptt3Ae5o",
    dateAdded: "2025-05-02",
  },
  {
    id: 46,
    title: "What Is SQL Injection? - Web Security Academy",
    description:
      "Explains the SQL injection vulnerability, showing how attackers can manipulate database queries and how developers can prevent these attacks.",
    category: "coding",
    categoryName: "Secure Coding",
    image: "https://img.youtube.com/vi/wX6tszfgYp4/hqdefault.jpg",
    duration: "7 min",
    level: "Intermediate",
    videoUrl: "https://www.youtube.com/embed/wX6tszfgYp4",
    dateAdded: "2025-05-02",
  },
  {
    id: 47,
    title: "Web App Penetration Testing",
    description: "Test web applications for security flaws.",
    category: "hacking",
    categoryName: "Ethical Hacking",
    image: "https://i.ytimg.com/vi/X4eRbHgRawI/hqdefault.jpg",
    duration: "15 min",
    level: "Advanced",
    videoUrl: "https://www.youtube.com/embed/X4eRbHgRawI",
    dateAdded: "2023-06-01",
  },
  {
    id: 48,
    title: "Tor vs VPN: Which to Use? (Privacy Tools Compared)",
    description:
      "Compares the Tor network and VPNs, discussing the pros and cons of each approach for anonymizing your online activity and protecting privacy.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://img.youtube.com/vi/Z5G2I18BUCg/hqdefault.jpg",
    duration: "8 min",
    level: "Intermediate",
    videoUrl: "https://www.youtube.com/embed/Z5G2I18BUCg",
    dateAdded: "2025-05-02",
  },
  {
    id: 49,
    title: "How to protect your privacy online",
    description:
      "A concise guide with practical steps to protect online privacy: using multiple email accounts, limiting data on social media, and avoiding unnecessary sharing.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://img.youtube.com/vi/JO55V34EnK8/hqdefault.jpg",
    duration: "3 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/JO55V34EnK8",
    dateAdded: "2025-05-02",
  },
  {
    id: 50,
    title: "Zero Trust Security Model Explained Simply",
    description:
      "Introduction to the zero-trust security model, explaining why traditional perimeter-based defenses are insufficient and how zero-trust principles work.",
    category: "network",
    categoryName: "Network Security",
    image: "https://img.youtube.com/vi/DQrvhow5pJA/hqdefault.jpg",
    duration: "6 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/DQrvhow5pJA",
    dateAdded: "2025-05-02",
  },
  {
    id: 51,
    title: "Ultimate Web Privacy & Security Guide 2024",
    description: "Deep dive into Tor, VPNs, and browser hardening techniques.",
    category: "privacy",
    categoryName: "Privacy Protection",
    duration: "16 min",
    level: "Intermediate",
    videoUrl: "https://www.youtube.com/embed/E3LVxDq-aBA",
    image: "https://i.ytimg.com/vi/E3LVxDq-aBA/hqdefault.jpg",
    dateAdded: "2023-04-10",
  },
  {
    id: 52,
    title: "How To Stay Compliant with Data Privacy Laws",
    description:
      "Overview of GDPR, CCPA and other regulations and how they affect data handling.",
    category: "privacy",
    categoryName: "Privacy Protection",
    duration: "12 min",
    level: "Intermediate",
    videoUrl: "https://www.youtube.com/embed/Wr4IcM4G7Ys",
    image: "https://i.ytimg.com/vi/Wr4IcM4G7Ys/hqdefault.jpg",
    dateAdded: "2023-05-15",
  },
  {
    id: 53,
    title: "Privacy-Focused Browsers",
    description: "Explore browsers designed for privacy.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/wX75Z-4MEoM/hqdefault.jpg",
    duration: "7 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/wX75Z-4MEoM",
    dateAdded: "2023-06-01",
  },
  {
    id: 54,
    title: "Secure Browsing: The Ultimate Privacy Guide (2024)",
    description:
      "How to configure browsers and extensions to maximize online privacy.",
    category: "privacy",
    categoryName: "Privacy Protection",
    duration: "18 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/74Q3tAWU-4M",
    image: "https://i.ytimg.com/vi/74Q3tAWU-4M/hqdefault.jpg",
    dateAdded: "2024-09-01",
  },
  {
    id: 55,
    title: "How to Enable BitLocker (Windows 10)",
    description:
      "Step-by-step guide on enabling BitLocker drive encryption in Windows to protect data on your computer in case the device is lost or stolen.",
    category: "basics",
    categoryName: "Cybersecurity Basics",
    image: "https://img.youtube.com/vi/PtMyu9xrJ_E/hqdefault.jpg",
    duration: "4 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/PtMyu9xrJ_E",
    dateAdded: "2025-05-02",
  },
  {
    id: 56,
    title: "Drive by download attack: What it is and how it works",
    description:
      "Describes drive-by download attacks, where malicious code is downloaded automatically from compromised websites, and how to avoid becoming a victim.",
    category: "hacking",
    categoryName: "Ethical Hacking",
    image: "https://img.youtube.com/vi/xL4DyblbnKg/hqdefault.jpg",
    duration: "3 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/xL4DyblbnKg",
    dateAdded: "2025-05-02",
  },
  {
    id: 57,
    title: "Tor Network for Anonymity",
    description: "Learn how to use Tor for anonymous browsing.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/QRYzre4bf7I/hqdefault.jpg",
    duration: "10 min",
    level: "Intermediate",
    videoUrl: "https://www.youtube.com/embed/QRYzre4bf7I",
    dateAdded: "2023-06-01",
  },
  {
    id: 58,
    title: "Top 5 Privacy-Focused Ad Blockers (2025)",
    description:
      "A hands-on review of the leading ad blockers—uBlock Origin, AdGuard, Privacy Badger—and how they protect your data.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://img.youtube.com/vi/2lisQQmWQkY/hqdefault.jpg",
    duration: "9 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/2lisQQmWQkY",
    dateAdded: "2025-01-15",
  },
  {
    id: 59,
    title: "Secure Messaging Apps Compared (2024)",
    description:
      "Comparison of top secure messaging apps—Signal, Telegram, WhatsApp—focusing on privacy and features.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://img.youtube.com/vi/yGXaAWbzl5A/hqdefault.jpg",
    duration: "9 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/embed/yGXaAWbzl5A",
    dateAdded: "2024-02-10",
  },
  {
    id: 60,
    title: "Top 8 steps to protect your online privacy tutorial",
    description:
      "These are the top 8 steps to protect your online privacy in a chronological order of importance and effectiveness.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/qhPe3rLEktE/hqdefault.jpg",
    duration: "10 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=qhPe3rLEktE",
    dateAdded: "2025-05-02",
  },
  {
    id: 61,
    title: "How to protect your online privacy in 2019 | Tutorial",
    description:
      "Learn how to best protect your online privacy in 2019 with this tutorial.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/lLessJ4R6w8/hqdefault.jpg",
    duration: "15 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=lLessJ4R6w8",
    dateAdded: "2025-05-02",
  },
  {
    id: 62,
    title:
      "Become Anonymous: The Ultimate Guide To Privacy, Security, & Anonymity",
    description:
      "The ultimate & complete guide to becoming anonymous, private, and secure on the internet.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/a1i-3xwcSGA/hqdefault.jpg",
    duration: "20 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=a1i-3xwcSGA",
    dateAdded: "2025-05-02",
  },
  {
    id: 63,
    title: "Online Privacy for Beginners",
    description: "Learn the basics of protecting your online privacy.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "10 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
  {
    id: 64,
    title: "How to Stay Safe Online",
    description:
      "A beginner's guide to staying safe online and protecting your personal information.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "8 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
  {
    id: 65,
    title: "Introduction to Cybersecurity",
    description:
      "An introduction to cybersecurity basics, including online privacy.",
    category: "basics",
    categoryName: "Cybersecurity Basics",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "12 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
  {
    id: 66,
    title: "Password Security Basics",
    description:
      "Learn how to create strong passwords to secure your online accounts.",
    category: "basics",
    categoryName: "Security Basics",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "6 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
  {
    id: 67,
    title: "What is Phishing and How to Avoid It",
    description:
      "Understand phishing attacks and learn how to recognize and avoid them.",
    category: "basics",
    categoryName: "Security Basics",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "7 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
  {
    id: 68,
    title: "Understanding Two-Factor Authentication",
    description:
      "Learn what two-factor authentication is and why it's important for securing your accounts.",
    category: "basics",
    categoryName: "Security Basics",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "5 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
  {
    id: 69,
    title: "Using VPNs for Privacy",
    description:
      "Learn how VPNs can help protect your online privacy and how to choose the right one.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "9 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
  {
    id: 72,
    title: "Advanced Threat Hunting and Anomaly Detection with Splunk UBA",
    description: "Master advanced threat hunting and anomaly detection techniques using Splunk User Behavior Analytics (UBA) to identify sophisticated cyber threats in enterprise environments.",
    category: "security",
    categoryName: "Threat Detection",
    image: "https://i.ytimg.com/vi/pYsTjWaq3vs/hqdefault.jpg",
    duration: "42 min",
    level: "Advanced",
    videoUrl: "https://www.youtube.com/watch?v=pYsTjWaq3vs",
    dateAdded: "2025-05-02"
  },
  {
    id: 71,
    title: "Protecting Your Webcam and Microphone",
    description:
      "Learn how to secure your webcam and microphone to prevent unauthorized access.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/mBC71jwddC8/hqdefault.jpg",
    duration: "6 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=mBC71jwddC8",
    dateAdded: "2025-05-02",
  },
  {
    id: 72,
    title: "Understanding Browser Privacy Settings",
    description:
      "Learn how to configure browser settings to enhance your online privacy.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "7 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
  {
    id: 73,
    title: "Using Encrypted Messaging Apps",
    description:
      "A beginner’s guide to using encrypted messaging apps like Signal for secure communication.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "10 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
  {
    id: 74,
    title: "Avoiding Public Wi-Fi Risks",
    description:
      "Learn the risks of using public Wi-Fi and how to protect yourself.",
    category: "network",
    categoryName: "Network Security",
    image: "https://i.ytimg.com/vi/IGG4tg8CRb4/hqdefault.jpg",
    duration: "6 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=IGG4tg8CRb4",
    dateAdded: "2025-05-02",
  },
  {
    id: 75,
    title: "Securing Your Home Network",
    description:
      "Essential tips to secure your home Wi-Fi network from unauthorized access.",
    category: "network",
    categoryName: "Network Security",
    image: "https://i.ytimg.com/vi/ivPptt3Ae5o/hqdefault.jpg",
    duration: "8 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=ivPptt3Ae5o",
    dateAdded: "2025-05-02",
  },
  {
    id: 76,
    title: "Understanding Cookies and Tracking",
    description:
      "An explanation of how cookies work and their role in online tracking.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "7 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
  {
    id: 77,
    title: "Using Password Managers",
    description:
      "Learn how to use password managers to securely store and manage your passwords.",
    category: "basics",
    categoryName: "Security Basics",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "6 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
  {
    id: 78,
    title: "Keeping Software Up to Date",
    description:
      "Understand why keeping software updated is crucial for security.",
    category: "basics",
    categoryName: "Security Basics",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "5 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
  {
    id: 79,
    title: "Recognizing Malware and How to Avoid It",
    description:
      "Learn how to identify and avoid malware to protect your devices.",
    category: "basics",
    categoryName: "Cybersecurity Basics",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "7 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
  {
    id: 80,
    title: "Understanding Data Breaches and How to Protect Yourself",
    description:
      "Learn about data breaches and steps to protect your personal information.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "8 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
  {
    id: 81,
    title: "Using Incognito Mode Correctly",
    description:
      "Understand what incognito mode does and how to use it effectively.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "5 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
  {
    id: 82,
    title: "Clearing Browser History and Cache",
    description:
      "Learn how to clear your browser history and cache to enhance privacy.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "6 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
  {
    id: 83,
    title: "Using Privacy-Focused Search Engines",
    description:
      "Discover privacy-focused search engines like DuckDuckGo and how to use them.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "7 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
  {
    id: 84,
    title: "Post-Quantum Cryptography: Opportunities and Challenges",
    description: "Explore the advantages, limitations, and powerful potential of post-quantum cryptography to secure systems against quantum computing threats.",
    category: "technical",
    categoryName: "Cryptography",
    image: "https://i.ytimg.com/vi/uE_Y1C4QPU8/hqdefault.jpg",
    duration: "21 min",
    level: "Advanced",
    videoUrl: "https://www.youtube.com/watch?v=uE_Y1C4QPU8",
    dateAdded: "2025-05-02"
  },
  {
    id: 85,
    title: "Protecting Your Children's Online Privacy",
    description: "Learn how to safeguard your children's online privacy.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/yiKeLOKc1tw/hqdefault.jpg",
    duration: "8 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=yiKeLOKc1tw",
    dateAdded: "2025-05-02",
  },
  {
    id: 86,
    title: "Securing Your Smartphone",
    description: "Essential tips to secure your smartphone from cyber threats.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/m_SN1CB3Kts/hqdefault.jpg",
    duration: "7 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=m_SN1CB3Kts",
    dateAdded: "2025-05-02",
  },
  {
    id: 87,
    title: "Using Secure Email Services",
    description:
      "Learn about secure email services like ProtonMail and how to use them.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "8 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
  {
    id: 88,
    title: "Understanding End-to-End Encryption",
    description:
      "Learn what end-to-end encryption is and why it matters for privacy.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "6 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
  {
    id: 89,
    title: "Avoiding Online Scams",
    description: "Learn how to identify and avoid common online scams.",
    category: "basics",
    categoryName: "Security Basics",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "7 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
  {
    id: 90,
    title: "Securing Your Online Banking",
    description:
      "Learn how to protect your online banking accounts from cyber threats.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/35ZrnxEHyl4/hqdefault.jpg",
    duration: "8 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=35ZrnxEHyl4",
    dateAdded: "2025-05-02",
  },
  {
    id: 91,
    title: "Using Antivirus Software",
    description:
      "Learn how to choose and use antivirus software to protect your devices.",
    category: "basics",
    categoryName: "Security Basics",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "6 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
  {
    id: 92,
    title: "Understanding Firewalls",
    description: "Learn what firewalls are and how they protect your network.",
    category: "basics",
    categoryName: "Security Basics",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "7 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
  {
    id: 93,
    title: "Protecting Your Identity Online",
    description:
      "Learn how to protect your personal identity from online threats.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "8 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
  {
    id: 94,
    title: "Using Secure Cloud Storage",
    description:
      "Learn how to use secure cloud storage services to protect your data.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "7 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
  {
    id: 95,
    title: "Understanding Tor and Anonymous Browsing",
    description: "Learn how to use the Tor browser for anonymous browsing.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "10 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
  {
    id: 96,
    title: "Avoiding Clickbait and Fake News",
    description:
      "Learn how to identify and avoid clickbait and fake news online.",
    category: "basics",
    categoryName: "Cybersecurity Basics",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "6 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
  {
    id: 97,
    title: "Securing Your Smart Home Devices",
    description:
      "Learn how to secure your smart home devices to protect your privacy.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/6UFTJQyFu1k/hqdefault.jpg",
    duration: "8 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=6UFTJQyFu1k",
    dateAdded: "2025-05-02",
  },
  {
    id: 98,
    title: "Understanding App Permissions",
    description: "Learn how to manage app permissions to enhance your privacy.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "7 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
  {
    id: 99,
    title: "Using Privacy-Focused Browsers",
    description:
      "Discover privacy-focused browsers like Brave and how to use them.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "8 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
  {
    id: 100,
    title: "Protecting Your Online Reputation",
    description:
      "Learn how to protect your online reputation and maintain a positive digital footprint.",
    category: "privacy",
    categoryName: "Privacy Protection",
    image: "https://i.ytimg.com/vi/-nv3IEtXhF8/hqdefault.jpg",
    duration: "10 min",
    level: "Beginner",
    videoUrl: "https://www.youtube.com/watch?v=-nv3IEtXhF8",
    dateAdded: "2025-05-02",
  },
];
